name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
          npm install --prefix apps/web
      - name: Bazel test
        run: bazel test //...
      - name: Lint
        run: make lint
      - name: Integration tests
        run: make test-integration
        env:
          GATEWAY_URL: http://localhost:8080
      - name: End-to-end tests
        run: make test-e2e
        env:
          GATEWAY_URL: http://localhost:8080
